version: "3"
services:
  postgres:
    restart: always
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:4.0
    restart: always
    ports:
      - "6379:6379"
volumes:
  pgdata:
