default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: udemy_portfolio_development
  username: postgres
  password: 123456
  host: localhost
  port: 5432

test:
  <<: *default
  database: udemy_portfolio_test
  username: postgres
  password: 123456
  host: localhost
  port: 5432

production:
  <<: *default
  database: udemy_portfolio_production
  username: udemy_portfolio
  password: <%= ENV['UDEMY_PORTFOLIO_DATABASE_PASSWORD'] %>
